apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Base64 encoded values for 'admin' and 'password'
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
